'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import type {BoardPost} from './BoardPostList';
import {makeHomeBoardPost} from '@/lib/home-board-post';
import hkFirst from '@/public/generated/home-board/type-1-pingte-one.json';
import macauFirst from '@/public/generated/home-board/type-5-pingte-one.json';
import dailyFirst from '@/public/generated/home-board/type-8-pingte-one.json';
type Category={key:string;label:string};type Data={total:number;page:number;pages:number;posts:BoardPost[]};type Manifest={issue:number;methods:Record<string,unknown>[]};
const firstBoards:Record<string,Manifest>={'1':hkFirst,'5':macauFirst,'8':dailyFirst};
// These small lists are regenerated by generate_home_board_data.py before every build.
// Keep server and initial browser render identical; only effects read the runtime cache.
const manifests=new Map<string,{value:Manifest;expires:number}>();
const CACHE_LIMIT=48,CACHE_TTL=5*60*1000;
function cached(key:string){const item=manifests.get(key);if(!item)return null;if(item.expires<=Date.now()){manifests.delete(key);return null;}manifests.delete(key);manifests.set(key,item);return item.value;}
function remember(key:string,value:Manifest){manifests.delete(key);manifests.set(key,{value,expires:Date.now()+CACHE_TTL});while(manifests.size>CACHE_LIMIT)manifests.delete(manifests.keys().next().value!);}
export default function RemoteBoard({type,board,version,categories=[{key:'',label:''}]}:{type:string;board:string;version:number;categories?:Category[]}){
  const [category,setCategory]=useState(categories[0].key),[page,setPage]=useState(1),[visible,setVisible]=useState(false),[error,setError]=useState(false);
  const key=board==='pingte'?`pingte-${category==='two'?'two':'one'}`:`${board}-${category}`;
  const url=`/generated/home-board/type-${type}-${key}.json?v=${version}`;
  const seed=board==='pingte'&&category==='one'&&firstBoards[type]?.issue===version?firstBoards[type]:null;
  const [loaded,setLoaded]=useState<{url:string;value:Manifest}|null>(null);
  const manifest=loaded?.url===url?loaded.value:seed;
  const data=useMemo<Data|null>(()=>{if(!manifest)return null;const pageSize=10,pages=Math.max(1,Math.ceil(manifest.methods.length/pageSize)),safe=Math.min(page,pages),start=(safe-1)*pageSize;return {total:manifest.methods.length,page:safe,pages,posts:manifest.methods.slice(start,start+pageSize).map((method,index)=>makeHomeBoardPost(type,board,category,manifest.issue,method,start+index))};},[manifest,page,type,board,category]);const root=useRef<HTMLDivElement>(null);
  useEffect(()=>{const el=root.current;if(!el)return;if(typeof IntersectionObserver==='undefined'){setVisible(true);return;}const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){setVisible(true);observer.disconnect();}},{rootMargin:'500px'});observer.observe(el);return()=>observer.disconnect()},[]);
  useEffect(()=>{
    if(!visible)return;
    const existing=cached(url);
    if(existing){setLoaded({url,value:existing});setError(false);return;}
    if(seed){remember(url,seed);setError(false);return;}
    const controller=new AbortController();
    fetch(url,{signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('读取失败');const value=await r.json() as Manifest;if(!Number.isInteger(value.issue)||!Array.isArray(value.methods))throw Error('清单格式错误');return value;}).then(value=>{if(controller.signal.aborted)return;remember(url,value);setLoaded({url,value});setError(false)}).catch(e=>{if(!controller.signal.aborted&&e.name!=='AbortError')setError(true)});
    return()=>controller.abort();
  },[visible,url,seed]);
  const pageNumbers=useMemo(()=>{const pages=data?.pages??1;if(pages<=5)return Array.from({length:pages},(_,i)=>i+1);const start=Math.min(Math.max(1,page-2),pages-4);return Array.from({length:5},(_,i)=>start+i)},[data?.pages,page]);
  const change=(key:string)=>{setCategory(key);setPage(1);setError(false)};
  return <div ref={root} className="remote-board">
    {categories.length>1&&<div className={`pingte-tabs ${board==='pingte'?'pingte-main-tabs':''} ${board==='tema'?'tema-tabs':''}`}>{categories.map(c=><button className={category===c.key?'active':''} onClick={()=>change(c.key)} key={c.key}>{c.label}</button>)}</div>}
    <div className="pingte-count">{data?`当前共 ${data.total} 条公式`:'正在读取公式…'}</div>
    {error?<div className="pingte-empty"><strong>读取失败</strong><button onClick={()=>{setVisible(false);requestAnimationFrame(()=>setVisible(true))}}>重新加载</button></div>:data?<><div className="board-titles">{data.posts.map(post=><a href={post.href} key={post.href}><span>{post.issue}</span><h3>{post.title}</h3><i>›</i></a>)}</div>{data.pages>1&&<nav className="board-pagination" aria-label="帖子分页"><button disabled={page===1} onClick={()=>setPage(v=>v-1)}>上一页</button>{pageNumbers.map(v=><button className={page===v?'active':''} onClick={()=>setPage(v)} key={v}>{v}</button>)}<button disabled={page===data.pages} onClick={()=>setPage(v=>v+1)}>下一页</button></nav>}</>:<div className="board-list-loading" aria-hidden="true"/>}
  </div>;
}
